apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openhands
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/openhands/ohs.git
    targetRevision: HEAD
    path: deploy/helm/openhands
    helm:
      valueFiles:
        - values.yaml
      # Optional: override values
      values: |
        replicaCount: 2
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: app.openhands.ai
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: openhands-tls
              hosts:
                - app.openhands.ai
  destination:
    server: https://kubernetes.default.svc
    namespace: openhands
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true