apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openhands.fullname" . }}-secrets
  labels:
    {{- include "openhands.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.config.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.enabled }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}
  {{- if .Values.redis.enabled }}
  REDIS_PASSWORD: {{ .Values.redis.auth.password | default (randAlphaNum 16) | b64enc | quote }}
  {{- end }}